#!/bin/zsh

URL="https://fitpulse-gym-app.hcalinoiu.chatgpt.site"

if [[ -d "/Applications/Google Chrome.app" ]]; then
  open -na "Google Chrome" --args --app="$URL"
elif [[ -d "/Applications/Microsoft Edge.app" ]]; then
  open -na "Microsoft Edge" --args --app="$URL"
else
  open "$URL"
fi
